# Generated by Django 3.2.25 on 2026-06-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0007_clientposts_model_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='predict_ev_energy_consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fid', models.CharField(max_length=300)),
                ('Vehicle_Model', models.CharField(max_length=300)),
                ('Battery_Capacity_kWh', models.CharField(max_length=300)),
                ('Charging_Station_ID', models.CharField(max_length=300)),
                ('Charging_Station_Location', models.CharField(max_length=300)),
                ('Charging_Start_Time', models.CharField(max_length=300)),
                ('Charging_EndTime', models.CharField(max_length=300)),
                ('Energy_Consumed_kWh', models.CharField(max_length=300)),
                ('Charging_Duration_hours', models.CharField(max_length=300)),
                ('Charging_Rate_kW', models.CharField(max_length=300)),
                ('Charging_Cost_USD', models.CharField(max_length=300)),
                ('Vehicle_Age_years', models.CharField(max_length=300)),
                ('Charger_Type', models.CharField(max_length=300)),
                ('User_Type', models.CharField(max_length=300)),
                ('Prediction', models.CharField(max_length=3000)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientposts_model',
            name='userId',
        ),
        migrations.DeleteModel(
            name='review_Model',
        ),
        migrations.AddField(
            model_name='clientregister_model',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='clientregister_model',
            name='gender',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='ClientPosts_Model',
        ),
    ]
